# Generated by Django 4.1.10 on 2023-07-16 00:04

import address.models
from django.db import migrations
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_auto_20200830_1851'),
        ('invoice', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='clientAddress',
        ),
        migrations.DeleteModel(
            name='senderAddress',
        ),
        migrations.AddField(
            model_name='invoice',
            name='clientAddress',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ClientAddress', to='address.address'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='senderAddress',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SenderAddress', to='address.address'),
        ),
    ]
